# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: ie-bank-frontend

on:
  push:
    branches:
      - '*' 
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  FRONTEND_WEBAPP_DEV: svitorica-fe-dev
  FRONTEND_WEBAPP_UAT: svitorica-fe-uat

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: npm install, build, and test (dev)
        run: |
          npm install
          npm run build -- --mode development --dest dist-dev ## this command will build the vue.js app using .env.development variables into the dest-div/ folder

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app-dev
          path: dist-dev/
      
      - name: npm install, build, and test (UAT)
        run: |
          npm install
          npm run build -- --mode uat --dest dist-uat ## this command will build the vue.js app using .env.development variables into the dest-div/ folder

      - name: Upload artifact for deployment job (UAT)
        uses: actions/upload-artifact@v4
        with:
          name: node-app-uat
          path: dist-uat/


  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app-dev

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_DEV }}
          package: .

  deploy-uat:
    runs-on: ubuntu-latest
    needs: [build, deploy-dev]
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'  # Only run UAT for PRs to main or main branch
    environment:
      name: 'UAT'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app-uat

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Deploy to Azure Web App - UAT'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_UAT }}
          package: .
